# This is a basic workflow that is manually triggered

name: DEPLOY TO DEDICATED SERVER
on:
  push:
    branches:
    - master
    - CI
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: /src
        remote_path: /home/demo/ebird-client
        remote_host: www.wyvernpserver.tech
        remote_port: 22
        remote_user: admin
        remote_key: ${{ secrets.DEPLOY_KEY }}
